name: Release

on:
  release:
    types:
      - published

jobs:
  release_to_pypi:
    name: Release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/flyweb-framework/
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Search and replace version
        run: |
          VERSION="${TAG_NAME//v/}"
          sed -i "s/^version = .*placeholder.*$/version = \"$VERSION\"/" pyproject.toml
          head pyproject.toml
        env:
          TAG_NAME: ${{ github.event.release.tag_name }}
      - uses: eifinger/setup-rye@v2
      - name: Pin python-version
        run: rye pin 3.10
      - name: Build
        run: rye build
      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1.8
